Feature/tests
the-man-w-laughs/Team-Task-Hub pull request #18
Opened 2023-11-29 11:45 UTC by the-man-w-laughs

Unit tests based on XUnit.

2023-12-16 20:22 UTC, katyalys requested changes

2023-12-16 20:22 UTC, katyalys commented on src/services/Identity/Identity.Tests/ControllerTests/UserControllerTests.cs
> +                .RuleFor(u => u.Email, f => f.Internet.Email())
make more explicit naming instead of u, f

2023-12-16 20:22 UTC, katyalys commented on src/services/Identity/Identity.Tests/Helpers/UserManagerHelper.cs
> +                        return IdentityResult.Success;
empty line before return

2023-12-16 20:22 UTC, katyalys commented on src/services/Identity/Identity.Tests/RepositoriesTests/UserRepositoryTests.cs
> +                null,
why do you pass null? why cant you mock all dependencies here?

2023-12-16 20:22 UTC, katyalys commented on src/services/Identity/Identity.Tests/RepositoriesTests/UserRepositoryTests.cs
> +            var targetRole = "admin";
create enum or constant class

2023-12-16 20:22 UTC, katyalys commented on src/services/Identity/Identity.Tests/ControllerTests/UserControllerTests.cs
> +                .RuleFor(u => u.Email, f => f.Internet.Email())
move fakers to helper classes

2023-12-16 20:22 UTC, katyalys commented on src/services/Identity/Identity.Tests/ServiceTests/EmailConfirmationServiceTests.cs
> +            null,
same

2023-12-16 20:22 UTC, katyalys commented on src/services/Identity/Identity.Tests/ServiceTests/EmailConfirmationServiceTests.cs
> +        var token = "valid_token";
https://andrewlock.net/creating-parameterised-tests-in-xunit-with-inlinedata-classdata-and-memberdata/ read about inline data, and pass some of your parameters through it in some of your tests

2023-12-16 20:22 UTC, katyalys commented on src/services/Identity/Identity.Tests/ServiceTests/UserServiceTests.cs
> +            .RuleFor(u => u.Id, f => f.Random.Number(max: int.MaxValue))
move to helper

2023-12-19 16:16 UTC, the-man-w-laughs commented on src/services/Identity/Identity.Tests/ControllerTests/UserControllerTests.cs
> +                .RuleFor(u => u.Email, f => f.Internet.Email())
I made separate classes for fakers.

2023-12-20 15:31 UTC, katyalys approved these changes

2023-12-24 16:44 UTC, merged